spring:
  application:
    name: banking-universal
  graphql:
    graphql:
      enabled: true
    schema:
      printer:
        enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    user:
      name: username
      password: password
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      springframework: info #Insert debug for debugging mode
service:
  signingSecret: ${SIGNING_SECRET}
  tokenValidity: ${TOKEN_VALIDITY}
  tokenSecret: ${TOKEN_SECRET}
  fastForexApiKey: ${FAST_FOREX_API_KEY}
  fastForexBaseUrl: ${FOREX_SERVICE_BASE_URL}
